---
############################################################
# set config file
############################################################

- name: mkdir shared/config
  become: yes
  file:
    path: /var/www/{{ __app_name }}/shared/config
    state: directory
    owner: "{{ __working_user }}"
    group: "{{ __working_user }}"
    mode: 0777
    # = chmod

# - name: Chmod of application current public
#   become: yes
#   file:
#     path: /var/www/{{ __app_name}}/current/public/
#     state: directory
#     owner: "{{ __working_user }}"
#     group: "{{ __working_user }}"
#     mode: 0777

- name: set master.key for credentials
  template:
    src: roles/7_config/templates/master.key.j2
    dest: /var/www/{{ __app_name }}/shared/config/master.key

- name: set .env for database.yml
  template:
    src: roles/7_config/templates/.env.j2
    dest: /var/www/{{ __app_name }}/shared/.env
       
- name: set database.yml
  template:
    src: roles/7_config/templates/database.yml.j2
    dest: /var/www/{{ __app_name }}/shared/config/database.yml






# - name: set master.key for credentials2
#   template:
#     src: roles/7_config/templates/master.key.j2
#     dest: /var/www/{{ __app_name }}/config/master.key

# - name: set master.key for credentials
#   template:
#     src: roles/7_config/templates/master.key.j2
#     dest: /var/www/{{ __app_name }}/config/master.key

# - name: set .env for database.yml
#   template:
#     src: roles/7_config/templates/.env.j2
#     dest: /var/www/{{ __app_name }}/.env
       



# - name: set environment
#   become: yes
#   template:
#     sec: roles/7_config/templates/environment
#     dest: /etc/
# - name: Auth environment
#   become: yes
#   file:
#     path: /etc/environment
#     owner: "{{ __working_user }}"
#     group: "{{ __working_user }}"
#     mode: 0777
#     # = chmod

# - name: set database.yml
#   template:
#     src: roles/7_config/templates/database.yml.j2
#     dest: /var/www/{{ __app_name }}/config/datab


############################################################
# set secret_key_base
############################################################

# - name: make secret
#   shell: |
#     bash -lc "rake secret"
#   args:
#   register: secret

# - name: output secret terminal
#   debug:
#     var: secret.stdout


# - name: set environment
#   become: yes
#   template:
#     src: roles/7_config/templates/environment.j2
#     dest: /etc/environment
#   tags: environment

# $ ansible-playbook -i hosts setting.yml --tags=environment


# ------------------------------


# - name: set master.key for credentials normal
#   template:
#     src: roles/7_config/templates/master.key.j2
#     dest: /var/www/{{ __app_name }}/config/master.key
#   tags: config_in_normal


# - name: set .env for database.yml
#   template:
#     src: roles/7_config/templates/.env.j2
#     dest: /var/www/{{ __app_name }}/.env