---
############################################################
# rails app config
############################################################
- name: mkdir & permission
  become: yes
  file:
    path: "{{ __app_dir }}"
    state: directory
    owner: "{{ __working_user }}"
    group: "{{ __working_user }}"
    mode: 0755
    # = chmod

- name: clone app from git
  git:
    repo: https://github.com/itsuki23/hitch_climb.git
    dest: "{{ __app_dir }}"


- name: app chown
  file:
    path: "{{ __app_dir }}"
    state: directory
    owner: "{{ __working_user }}"
    group: "{{ __working_user }}"
    recurse: yes

# - name: set master.key for credentials
#   template:
#     src: roles/6_config/templates/master.key
#     dest: "{{ __app_secret_key_dir }}"

# - name: set .env for database.yml
#   template:
#     src: roles/6_config/templates/master.key
#     dest: "{{ __app_secret_key_dir }}"
       

# - name: bundle install
#   command: bundle install --path vendor/bundle
#   args:
#     chdir: "{{ __app_dir }}"

# - name: db_create
#   command: bundle exec rails db:create RAILS_ENV=production
#   args:
#     chdir: "{{ __app_dir }}"

# - name: db_migrate
#   command: bundle exec rails db:migrate RAILS_ENV=production
#   args:
#     chdir: "{{ __app_dir }}"

# - name: assets_precompile
#   command: bundle exec rails assets:precompile RAILS_ENV=production
#   args:
#     chdir: "{{ __app_dir }}"



# - name: bundle install
#   shell: |
#     bash -lc  "bundle install --path vendor/bundle"
#   args:
#     chdir: "{{ __app_dir }}"

# - name: db_create
#   shell: |
#     bash -lc  "bundle exec rails db:create RAILS_ENV=production"
#   args:
#     chdir: "{{ __app_dir }}"

# - name: db_migrate
#   shell: |
#     bash -lc  "bundle exec rails db:migrate RAILS_ENV=production"
#   args:
#     chdir: "{{ __app_dir }}"

# - name: assets_precompile
#   shell: |
#     bash -lc  "bundle exec rails assets:precompile RAILS_ENV=production"
#   args:
#     chdir: "{{ __app_dir }}"



# bundle install , rails db:create rails db:migrata
       
       