---
############################################################
# rbenv
############################################################
- name: install rbenv
  become: yes
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /usr/local/rbenv

# echo $PATH => ls user/local/bin/
- name: path for rbenv
  become: yes
  template:
    src: roles/4_ruby/templates/rbenv_path.sh.j2
    dest: /etc/profile.d/rbenv.sh
    owner: "{{ __working_user }}"
    group: "{{ __working_user }}"
    # mode: 0755

- name: activate path for rbenv
  shell: |
    bash -lc  "source ~/.bash_profile"

  # /bin/bash -lc  "source /etc/profile.d/rbenv.sh"
  # become: no
  # when: current_ruby_version.stdout != __version

############################################################
# ruby-build
############################################################

- name: install ruby-build
  become: yes
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /usr/local/rbenv/plugins/ruby-build

############################################################
# ruby
############################################################

- name: install ruby
  become: yes
  shell: bash -lc "rbenv install -s "{{ __ruby_version }}" "

- name: global & rehash
  become: yes
  shell: bash -lc "rbenv global "{{ __ruby_version }}" && rbenv rehash"

- name: check current ruby version
  shell: |
    bash -lc "ruby -v"
  args:
  register: ruby_version
  become_user: "{{ __working_user }}"
  changed_when: False

- name: ruby -v
  debug:
    var: ruby_version.stdout

  # shellはbin/shを使うので明示的にbashを指定(-lc "  ")
  # grep -o(only matching) P(Perl正規表現) ruby(以外) \d(単数指定) {1}(1文字)
  # cut(必要な情報だけ切り取る) -f(field:項目数指定) 2(2項目目) -d(?) ␣('')で区切った
  # changed_when: falseにすると実行後にchangeにカウントされない

############################################################
# gem bundler global
############################################################
- name: install bundler
  become: yes
  shell: bash -lc "gem install bundler -v "{{__bundler_version}}" "

- name: Install Rails
  become: yes
  shell: bash -lc "gem install rails -v "{{ __rails_version }}" "

