AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3



# ------------------------------------------------------------ #
    # Edit Project name → [  taskleaf  ]
# ------------------------------------------------------------ #
Resources:
  S3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: taskleaf-s3-2
      AccessControl: Private
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3
      PolicyDocument:
        Statement:
          Action:
             - s3:GetObject
          Effect: "Allow"
          Resource: !Sub arn:aws:s3:::taskleaf-s3/*
          Principal: "*"
 

 
Outputs:
  S3BucketName:
    Value: !Ref S3

